### ISSUE TITLE
Login_actualizado

### ISSUE THREAD

**Issue by IreneLeon23** [IreneLeon23/Leon_parcial_2#2]
Crendenciales: 
usuario: ingreyeslara
contraseña: Utd_2024

**Comment by ingreyeslara** [comment]
El login si funciona, pero en la segunda pantalla no se ve nada
![leon](https://github.com/IreneLeon23/Leon_parcial_2/assets/75334788/d021f51f-aa1e-44e6-8891-dabdaca8ca5f)

**Comment by IreneLeon23** [comment]
Listo @ingreyeslara

**Comment by ingreyeslara** [comment]
CORRECTO,LIBERADO!!!!!
